AllCops:
  TargetRubyVersion: 3.0

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Layout/IndentationStyle:
  Enabled: true
  IndentationWidth: 2
  EnforcedStyle: spaces

Style/SingleLineMethods:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

# Style/TrailingBodyOnMethodDefinition:
#   Enabled: false
